---
- name: "Stop domain for {{ item }}"
  community.libvirt.virt:
    name: "{{ item }}"
    state: destroyed
    uri: "{{ _mp_specs[item].uri | default('qemu:///session') }}"
  failed_when: false

- name: "Undefine domain for {{ item }}"
  community.libvirt.virt:
    name: "{{ item }}"
    command: undefine
    uri: "{{ _mp_specs[item].uri | default('qemu:///session') }}"
  failed_when: false

- name: "Remove volume for {{ item }}"
  community.libvirt.virt_volume:
    command: delete
    pool: "molecule-{{ molecule_ephemeral_directory | basename }}"
    name: "{{ item }}.qcow2"
    uri: "{{ _mp_specs[item].uri | default('qemu:///session') }}"
  failed_when: false

- name: "Remove libvirt-driver artifacts for {{ item }}"
  ansible.builtin.file:
    path: "{{ molecule_ephemeral_directory }}/{{ item }}{{ ext }}"
    state: absent
  loop:
    - ".qcow2"
    - ".domain.xml"
    - "-seed.iso"
  loop_control:
    loop_var: ext
