---
driver:
  name: default
  options:
    managed: true
    ansible_connection_options:
      connection: ssh

platforms:
  - name: ubuntu-24
    kubevirt:
      image: quay.io/containerdisks/ubuntu:24.04
      namespace: "${MOLECULE_NAMESPACE:-molecule}"
      ssh_service:
        type: NodePort
      ansible_user: cloud-user
      memory: 4Gi
      disk_size: 30Gi
  - name: centos-stream-10
    kubevirt:
      image: quay.io/containerdisks/centos-stream:10
      namespace: "${MOLECULE_NAMESPACE:-molecule}"
      ssh_service:
        type: NodePort
      ansible_user: cloud-user
      memory: 4Gi
      disk_size: 30Gi

provisioner:
  name: ansible
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  env:
    PROVISIONER: kubevirt
  inventory:
    links:
      group_vars: group_vars/

verifier:
  name: ansible

scenario:
  name: kubevirt
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
