---
driver:
  name: default
  options:
    managed: true
    ansible_connection_options:
      connection: ssh

platforms:
  - name: fedora-emu
    kubevirt:
      image: quay.io/kubevirt/fedora-cloud-container-disk-demo:latest
      namespace: "${MOLECULE_NAMESPACE:-molecule}"
      ssh_service:
        type: NodePort
      ansible_user: cloud-user
      memory: 1Gi
      disk_size: 5Gi

provisioner:
  name: ansible
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  env:
    PROVISIONER: kubevirt
  inventory:
    links:
      group_vars: group_vars/

verifier:
  name: ansible

scenario:
  name: kubevirt_ci
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
