---
- name: Initialize podman network list
  ansible.builtin.set_fact:
    __mp_podman_networks: []

- name: Collect networks from per-host podman_network
  ansible.builtin.set_fact:
    __mp_podman_networks: >-
      {{ __mp_podman_networks +
         (_mp_specs[item].podman_network
          if (_mp_specs[item].podman_network is sequence
              and _mp_specs[item].podman_network is not string)
          else [_mp_specs[item].podman_network]) }}
  loop: "{{ groups['molecule'] }}"
  loop_control:
    label: "{{ item }}"
  when:
    - _mp_specs[item].podman_network is defined
    - _mp_specs[item].podman_network
