---
- name: Build podman network list
  ansible.builtin.import_tasks: _networks.yml

- name: Create podman network(s)
  containers.podman.podman_network:
    name: "{{ item }}"
    state: present
  loop: "{{ __mp_podman_networks | default([]) | unique }}"
  when:
    - __mp_podman_networks | default([]) | length > 0
    - item not in mp_podman_reserved_networks
    - item is not match('^ns:')
    - item is not match('^container:')

- name: Create molecule instance(s)
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.podman.image }}"
    state: started
    recreate: false
    command: "{{ item.podman.command | default(omit) }}"
    privileged: "{{ item.podman.privileged | default(false) }}"
    volume: "{{ item.podman.volumes | default(omit) }}"
    cap_add: "{{ item.podman.capabilities | default(omit) }}"
    expose: "{{ item.podman.exposed_ports | default(omit) }}"
    publish: "{{ item.podman.published_ports | default(omit) }}"
    network: "{{ item.podman.podman_network | default(omit) }}"
    env: "{{ item.podman.env | default({}) }}"
    tmpfs: "{{ item.podman.tmpfs | default(omit) }}"
  register: __mp_podman_create
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    label: "{{ item.name }}"
  async: "{{ mp_podman_async_timeout }}"
  poll: 0

- name: Wait for instance(s) creation to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: __mp_podman_jobs
  until: __mp_podman_jobs.finished
  retries: "{{ mp_podman_async_retries }}"
  loop: "{{ __mp_podman_create.results }}"
  loop_control:
    label: "{{ item.item.name }}"
