---
all:
  children:
    molecule:
      hosts:
        ubuntu-libvirt-slirp:
          mp:
            qemu:
              image: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
              image_checksum: "sha256:6e7016f2c9f4d3c00f48789eb6b9043ba2172ccc1b6b1eaf3ed1e29dd3e52bb3"
              driver: libvirt
              uri: qemu:///session
              network:
                mode: slirp
        ubuntu-process-slirp:
          mp:
            qemu:
              image: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
              image_checksum: "sha256:6e7016f2c9f4d3c00f48789eb6b9043ba2172ccc1b6b1eaf3ed1e29dd3e52bb3"
              driver: process
              network:
                mode: slirp
        ubuntu-libvirt-nat:
          mp:
            qemu:
              image: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
              image_checksum: "sha256:6e7016f2c9f4d3c00f48789eb6b9043ba2172ccc1b6b1eaf3ed1e29dd3e52bb3"
              driver: libvirt
              uri: qemu:///system
              network:
                mode: nat
