---
galaxy_info:
  role_name: podman
  author: David Igou
  description: Molecule provisioner role using containers.podman
  company: ""
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: GenericLinux
      versions: [all]
  galaxy_tags:
    - molecule
    - podman
    - testing
dependencies: []
