---
- name: Verify each host has sudo installed (prepare side-effect)
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Check sudo
      ansible.builtin.command: which sudo
      changed_when: false
